## TODO: add a compose examples directory with various deployment options.
version: "3"
services:
  redis:
    image: redis
  mongo:
    image: mongo
    volumes:
      - "./data/mongo:/data"
  ohmyform:
    image: ohmyform/ohmyform
    #build: .
    #volumes:
    #  - ".:/opt/app"
    environment:
      CREATE_ADMIN: "TRUE"
      SOCKET_URL: 'localhost:5000'
      SOCKET_PORT: "5000"
      SOCKET_PORT_EXTERN_VISIBLE: "TRUE"
      MONGODB_URI: mongodb://mongo/ohmyform
      REDIS_URL: redis://redis
      MAILER_SMTP_HOST: mail
      MAILER_SMTP_PORT: 1025
    # command: grunt dev # override command to have livereloading on file change
    links:
      - mongo
      - redis
      - mail
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  mail:
    image: mailhog/mailhog
    ports:
      - "5050:8025"
  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "5051:8081"
    links:
      - mongo
    depends_on:
      - mongo
